# Generated by Django 5.2.13 on 2026-06-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula_profesional',
            field=models.CharField(blank=True, default='', help_text='Cédula del psicólogo/consultor responsable. Vacía = no puede aprobar reportes psicológicos.', max_length=30, verbose_name='Cédula profesional'),
        ),
    ]
