# Generated by Django 5.2.13 on 2026-04-17 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Razon social')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('giro', models.CharField(max_length=200, verbose_name='Giro o actividad')),
                ('num_trabajadores', models.PositiveIntegerField(verbose_name='Numero de trabajadores')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('consultor', models.ForeignKey(limit_choices_to={'rol': 'super_admin'}, on_delete=django.db.models.deletion.PROTECT, related_name='tenants_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Consultor asignado')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
    ]
