# Generated by Django 5.2.13 on 2026-04-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='direccion',
            field=models.CharField(blank=True, max_length=400, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='URL del logo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefono de contacto'),
        ),
    ]
