# Generated by Django 5.2.13 on 2026-07-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_direcciones_plantas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razon social para informes. Si se deja vacia se usa el nombre del centro.', max_length=300, verbose_name='Razon social'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del centro de trabajo'),
        ),
    ]
