# Generated by Django 5.2.13 on 2026-08-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_razon_social_alter_tenant_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razon social para informes. Si se deja vacia se usa la razon social corporativa por defecto (CONSORCIO INDUSTRIAL MEXICANO DE AUTOPARTES).', max_length=300, verbose_name='Razon social'),
        ),
    ]
