# Generated by Django 5.2.13 on 2026-04-18 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m00_onboarding', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPrevension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Política de Prevención de Factores de Riesgo Psicosocial', max_length=300)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('vigente', 'Vigente'), ('archivada', 'Archivada')], default='borrador', max_length=20)),
                ('firmante_nombre', models.CharField(blank=True, max_length=200)),
                ('firmante_puesto', models.CharField(blank=True, max_length=200)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas', to='m00_onboarding.ciclonom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-ciclo__anio'],
                'unique_together': {('tenant', 'ciclo')},
            },
        ),
    ]
