# Generated by Django 5.2.13 on 2026-04-18 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m00_onboarding', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('modulo', models.CharField(choices=[('comite', 'Comite NOM-035'), ('plan', 'Plan de Accion'), ('politica', 'Politica de Prevencion'), ('difusion', 'Difusion'), ('aplicacion', 'Aplicacion de Cuestionarios'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='evidencias/%Y/%m/')),
                ('tamanio', models.PositiveIntegerField(default=0)),
                ('tipo_mime', models.CharField(blank=True, max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='m00_onboarding.ciclonom')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
