# Generated by Django 5.2.13 on 2026-04-18 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m00_onboarding', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comite', 'Reunion de Comite'), ('capacitacion', 'Sesion de Capacitacion'), ('seguimiento', 'Reunion de Seguimiento'), ('informativa', 'Sesion Informativa'), ('otra', 'Otra')], default='otra', max_length=20)),
                ('titulo', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('agenda', models.TextField(blank=True)),
                ('minuta', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='m00_onboarding.ciclonom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('puesto', models.CharField(blank=True, max_length=200)),
                ('firma_recibida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='m08_attendance.reunion')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
