# Generated by Django 5.2.13 on 2026-04-18 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m00_onboarding', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComiteNOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_constitucion', models.DateField()),
                ('numero_acta', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comites', to='m00_onboarding.ciclonom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-ciclo__anio'],
                'unique_together': {('tenant', 'ciclo')},
            },
        ),
        migrations.CreateModel(
            name='MiembroComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('puesto', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('presidente', 'Presidente'), ('secretario', 'Secretario'), ('vocal', 'Vocal')], default='vocal', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='m01_committee.comitenom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CapacitacionDC3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_capacitacion', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('horas', models.PositiveSmallIntegerField(default=8)),
                ('instructor', models.CharField(blank=True, max_length=200)),
                ('numero_dc3', models.CharField(blank=True, max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='m01_committee.miembrocomite')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
