# Generated by Django 5.2.13 on 2026-04-18 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m00_onboarding', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadDifusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('platica', 'Platica / Capacitacion'), ('correo', 'Correo electronico'), ('cartel', 'Cartel / Material impreso'), ('reunion', 'Reunion de trabajo'), ('intranet', 'Intranet / Portal interno'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('num_participantes', models.PositiveSmallIntegerField(default=0)),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_difusion', to='m00_onboarding.ciclonom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
