# Generated by Django 5.2.13 on 2026-06-22 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m00_onboarding', '0007_trabajador_tipo_jornada_tiempo_completo'),
        ('tenants', '0003_tenant_etiquetas_cortas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePsicologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado')], default='borrador', max_length=20)),
                ('anonimo', models.BooleanField(default=False)),
                ('generado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre_revisor', models.CharField(blank=True, default='', max_length=200)),
                ('cedula_revisor', models.CharField(blank=True, default='', max_length=30)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('contenido_html_final', models.TextField(blank=True, null=True)),
                ('ciclo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_psicologico', to='m00_onboarding.ciclonom')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_psico_generados', to=settings.AUTH_USER_MODEL)),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_psico_revisados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Reporte psicológico',
                'verbose_name_plural': 'Reportes psicológicos',
                'ordering': ['-ciclo__anio'],
            },
        ),
    ]
