# Generated by Django 5.2.13 on 2026-04-18 00:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m00_onboarding', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tamano_min', models.PositiveIntegerField()),
                ('tamano_max', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
                'ordering': ['tamano_min'],
            },
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='m00_onboarding.ciclonom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='m00_onboarding.trabajador')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='m05_questionnaires.cuestionario')),
            ],
            options={
                'verbose_name': 'Aplicacion',
                'verbose_name_plural': 'Aplicaciones',
                'ordering': ['trabajador__apellido_paterno', 'trabajador__nombre'],
                'unique_together': {('ciclo', 'cuestionario', 'trabajador')},
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='m05_questionnaires.cuestionario')),
            ],
            options={
                'verbose_name': 'Dominio',
                'ordering': ['orden'],
                'unique_together': {('cuestionario', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('texto', models.TextField()),
                ('inversa', models.BooleanField(default=False)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='m05_questionnaires.dominio')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'ordering': ['orden'],
                'unique_together': {('dominio', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('valor', models.PositiveSmallIntegerField(choices=[(0, 'Nunca'), (1, 'Casi nunca'), (2, 'Algunas veces'), (3, 'Casi siempre'), (4, 'Siempre')])),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='m05_questionnaires.aplicacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m05_questionnaires.pregunta')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'unique_together': {('aplicacion', 'pregunta')},
            },
        ),
    ]
