# Generated by Django 5.2.13 on 2026-05-05 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m00_onboarding', '0001_initial'),
        ('m05_questionnaires', '0001_initial'),
        ('tenants', '0002_tenant_direccion_tenant_logo_url_tenant_sitio_web_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guia_links', to='m00_onboarding.ciclonom')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guia_links', to='m05_questionnaires.cuestionario')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Link de Guia',
                'verbose_name_plural': 'Links de Guia',
                'unique_together': {('ciclo', 'cuestionario')},
            },
        ),
    ]
