# Generated by Django 5.2.13 on 2026-05-05 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m05_questionnaires', '0002_guialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='condicion_pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_condicionadas', to='m05_questionnaires.pregunta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='condicion_valor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_respuesta',
            field=models.CharField(choices=[('frecuencia', 'Frecuencia'), ('si_no', 'Si/No')], default='frecuencia', max_length=20),
        ),
    ]
