# Generated by Django 5.2.13 on 2026-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m05_questionnaires', '0003_pregunta_condicion_pregunta_pregunta_condicion_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='condicion_operador',
            field=models.CharField(choices=[('all', 'Todas'), ('any', 'Cualquiera')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='condicion_preguntas',
            field=models.ManyToManyField(blank=True, related_name='preguntas_condicionadas_multiples', to='m05_questionnaires.pregunta'),
        ),
    ]
