# Generated by Django 5.2.13 on 2026-05-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m05_questionnaires', '0004_pregunta_condicion_operador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='opciones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='respuestapregunta',
            name='valor_texto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo_respuesta',
            field=models.CharField(choices=[('frecuencia', 'Frecuencia'), ('si_no', 'Si/No'), ('texto', 'Texto'), ('opcion', 'Opcion')], default='frecuencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='valor',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Nunca'), (1, 'Casi nunca'), (2, 'Algunas veces'), (3, 'Casi siempre'), (4, 'Siempre')], null=True),
        ),
    ]
