# Generated by Django 5.2.13 on 2026-07-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m05_questionnaires', '0006_aplicacionfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionfoto',
            name='miniatura',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplicacionfoto',
            name='miniatura_tamanio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
