# Generated by Django 5.2.13 on 2026-04-17 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido materno')),
                ('num_empleado', models.CharField(blank=True, max_length=30, verbose_name='No. de empleado')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico')),
                ('puesto', models.CharField(max_length=200, verbose_name='Puesto / cargo')),
                ('area', models.CharField(max_length=200, verbose_name='Area / departamento')),
                ('tipo_contratacion', models.CharField(choices=[('planta', 'Planta'), ('eventual', 'Eventual'), ('subcontratado', 'Subcontratado')], default='planta', max_length=20, verbose_name='Tipo de contratacion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CicloNOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('cerrado', 'Cerrado')], default='iniciado', max_length=20)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Ciclo NOM-035',
                'verbose_name_plural': 'Ciclos NOM-035',
                'ordering': ['-anio'],
                'unique_together': {('tenant', 'anio')},
            },
        ),
    ]
