# Generated by Django 5.2.13 on 2026-05-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m00_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electronico'),
        ),
    ]
