# Generated by Django 5.2.13 on 2026-05-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m00_onboarding', '0002_alter_trabajador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('union_libre', 'Union libre'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo'), ('otro', 'Otro')], max_length=20, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='experiencia_anios',
            field=models.FloatField(blank=True, null=True, verbose_name='Experiencia en anos'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='nivel_estudios',
            field=models.CharField(blank=True, choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato / Preparatoria'), ('tecnico', 'Tecnico'), ('licenciatura', 'Licenciatura'), ('ingenieria', 'Ingenieria'), ('posgrado', 'Posgrado'), ('otro', 'Otro')], max_length=20, verbose_name='Nivel de estudios'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='rotacion_turnos',
            field=models.BooleanField(blank=True, null=True, verbose_name='Realiza rotacion de turnos'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tiempo_puesto_actual',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo en puesto actual'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipo_jornada',
            field=models.CharField(blank=True, choices=[('diurno', 'Diurno'), ('mixto', 'Mixto'), ('nocturno', 'Nocturno')], max_length=10, verbose_name='Tipo de jornada'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipo_personal',
            field=models.CharField(blank=True, choices=[('sindicalizado', 'Sindicalizado / Directo'), ('confianza', 'Confianza / Indirecto'), ('salary', 'Salary / Administrativo'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de personal'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='area',
            field=models.CharField(blank=True, max_length=200, verbose_name='Area / departamento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='puesto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Puesto / cargo'),
        ),
    ]
