CUESTIONARIOS = [
    {
        'clave': 'V',
        'nombre': 'Datos del trabajador',
        'descripcion': 'Guia de Referencia V - Datos del trabajador.',
        'tamano_min': 1,
        'tamano_max': None,
        'dominios': [
            {
                'clave': 'D1',
                'nombre': 'Datos del trabajador',
                'preguntas': [
                    {'ref': 'V_P1', 'texto': 'Nombre completo', 'tipo_respuesta': 'texto'},
                    {'ref': 'V_P2', 'texto': 'Fecha (dia / mes / año)', 'tipo_respuesta': 'texto'},
                    {'ref': 'V_P3', 'texto': 'Sexo', 'tipo_respuesta': 'opcion', 'opciones': ['Masculino', 'Femenino']},
                    {'ref': 'V_P4', 'texto': 'Edad (años completos)', 'tipo_respuesta': 'texto'},
                    {'ref': 'V_P5', 'texto': 'Estado civil', 'tipo_respuesta': 'opcion', 'opciones': ['Casado', 'Divorciado', 'Soltero', 'Viudo', 'Union libre']},
                    {'ref': 'V_P6', 'texto': 'Ultimo nivel de estudios', 'tipo_respuesta': 'opcion', 'opciones': ['Sin formacion', 'Primaria', 'Secundaria', 'Preparatoria', 'Tecnico superior', 'Licenciatura', 'Maestria', 'Doctorado']},
                    {'ref': 'V_P7', 'texto': 'Ocupacion / profesion / puesto', 'tipo_respuesta': 'texto'},
                    {'ref': 'V_P8', 'texto': 'Departamento / Seccion / Area', 'tipo_respuesta': 'texto'},
                    {'ref': 'V_P9', 'texto': 'Tipo de puesto', 'tipo_respuesta': 'opcion', 'opciones': ['Operativo', 'Supervisor', 'Profesional o tecnico', 'Gerente']},
                    {'ref': 'V_P10', 'texto': 'Tipo de contratacion', 'tipo_respuesta': 'opcion', 'opciones': ['Por obra o proyecto', 'Tiempo indeterminado', 'Por tiempo determinado temporal', 'Honorarios']},
                    {'ref': 'V_P11', 'texto': 'Tipo de personal', 'tipo_respuesta': 'opcion', 'opciones': ['Sindicalizado', 'Confianza', 'Ninguno']},
                    {'ref': 'V_P12', 'texto': 'Tipo de jornada', 'tipo_respuesta': 'opcion', 'opciones': ['Fijo nocturno', 'Fijo mixto', 'Fijo diurno']},
                    {'ref': 'V_P13', 'texto': 'Rotacion de turnos', 'tipo_respuesta': 'si_no'},
                    {'ref': 'V_P14', 'texto': 'Experiencia en el puesto actual', 'tipo_respuesta': 'texto'},
                    {'ref': 'V_P15', 'texto': 'Tiempo de experiencia laboral total', 'tipo_respuesta': 'texto'},
                ],
            },
        ],
    },
    {
        'clave': 'I',
        'nombre': 'Acontecimientos traumaticos severos',
        'descripcion': 'Guia de Referencia I - Acontecimientos traumaticos severos.',
        'tamano_min': 1,
        'tamano_max': None,
        'dominios': [
            {
                'clave': 'D1',
                'nombre': 'Seccion I: Acontecimientos traumaticos severos',
                'preguntas': [
                    {'ref': 'I_S1_P1', 'texto': 'Accidente que tenga como consecuencia la muerte, la perdida de un miembro o una lesion grave.', 'tipo_respuesta': 'si_no'},
                    {'ref': 'I_S1_P2', 'texto': 'Asaltos.', 'tipo_respuesta': 'si_no'},
                    {'ref': 'I_S1_P3', 'texto': 'Actos violentos que derivaron en lesiones graves.', 'tipo_respuesta': 'si_no'},
                    {'ref': 'I_S1_P4', 'texto': 'Secuestro.', 'tipo_respuesta': 'si_no'},
                    {'ref': 'I_S1_P5', 'texto': 'Amenazas.', 'tipo_respuesta': 'si_no'},
                    {'ref': 'I_S1_P6', 'texto': 'Cualquier otro que ponga en riesgo su vida o salud, y/o la de otras personas.', 'tipo_respuesta': 'si_no'},
                ],
            },
            {
                'clave': 'D2',
                'nombre': 'Seccion II: Recuerdos persistentes sobre el acontecimiento',
                'preguntas': [
                    {'ref': 'I_S2_P1', 'texto': 'Ha tenido recuerdos recurrentes sobre el acontecimiento que le provocan malestares?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                    {'ref': 'I_S2_P2', 'texto': 'Ha tenido suenos de caracter recurrente sobre el acontecimiento, que le producen malestar?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                ],
            },
            {
                'clave': 'D3',
                'nombre': 'Seccion III: Esfuerzo por evitar circunstancias parecidas o asociadas al acontecimiento',
                'preguntas': [
                    {'ref': 'I_S3_P1', 'texto': 'Se ha esforzado por evitar todo tipo de sentimientos, conversaciones o situaciones que le puedan recordar el acontecimiento?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                    {'ref': 'I_S3_P2', 'texto': 'Se ha esforzado por evitar todo tipo de actividades, lugares o personas que motivan recuerdos del acontecimiento?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                    {'ref': 'I_S3_P3', 'texto': 'Ha tenido dificultad para recordar alguna parte importante del evento?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                    {'ref': 'I_S3_P4', 'texto': 'Ha disminuido su interes en sus actividades cotidianas?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                    {'ref': 'I_S3_P5', 'texto': 'Se ha sentido usted alejado o distante de los demas?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                    {'ref': 'I_S3_P6', 'texto': 'Ha notado que tiene dificultad para expresar sus sentimientos?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                    {'ref': 'I_S3_P7', 'texto': 'Ha tenido la impresion de que su vida se va a acortar, que va a morir antes que otras personas o que tiene un futuro limitado?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                ],
            },
            {
                'clave': 'D4',
                'nombre': 'Seccion IV: Afectacion',
                'preguntas': [
                    {'ref': 'I_S4_P1', 'texto': 'Ha tenido usted dificultades para dormir?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                    {'ref': 'I_S4_P2', 'texto': 'Ha estado particularmente irritable o le han dado arranques de coraje?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                    {'ref': 'I_S4_P3', 'texto': 'Ha tenido dificultad para concentrarse?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                    {'ref': 'I_S4_P4', 'texto': 'Ha estado nervioso o constantemente en alerta?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                    {'ref': 'I_S4_P5', 'texto': 'Se ha sobresaltado facilmente por cualquier cosa?', 'tipo_respuesta': 'si_no', 'condicion_refs': ['I_S1_P1', 'I_S1_P2', 'I_S1_P3', 'I_S1_P4', 'I_S1_P5', 'I_S1_P6'], 'condicion_operador': 'any', 'condicion_valor': 1},
                ],
            },
        ],
    },
]

GUIA_III_BASE = [
    'El espacio donde trabajo me permite realizar mis actividades de manera segura e higienica.',
    'Mi trabajo me exige hacer mucho esfuerzo fisico.',
    'Me preocupa sufrir un accidente en mi trabajo.',
    'Considero que en mi trabajo se aplican las normas de seguridad y salud en el trabajo.',
    'Considero que las actividades que realizo son peligrosas.',
    'Por la cantidad de trabajo que tengo debo quedarme tiempo adicional a mi turno.',
    'Por la cantidad de trabajo que tengo debo trabajar sin parar.',
    'Considero que es necesario mantener un ritmo de trabajo acelerado.',
    'Mi trabajo exige que este muy concentrado.',
    'Mi trabajo requiere que memorice mucha informacion.',
    'En mi trabajo tengo que tomar decisiones dificiles muy rapido.',
    'Mi trabajo exige que atienda varios asuntos al mismo tiempo.',
    'En mi trabajo soy responsable de cosas de mucho valor.',
    'Respondo ante mi jefe por los resultados de toda mi area de trabajo.',
    'En el trabajo me dan ordenes contradictorias.',
    'Considero que en mi trabajo me piden hacer cosas innecesarias.',
    'Trabajo horas extras mas de tres veces a la semana.',
    'Mi trabajo me exige laborar en dias de descanso, festivos o fines de semana.',
    'Considero que el tiempo en el trabajo es mucho y perjudica mis actividades familiares o personales.',
    'Debo atender asuntos de trabajo cuando estoy en casa.',
    'Pienso en las actividades familiares o personales cuando estoy en mi trabajo.',
    'Pienso que mis responsabilidades familiares afectan mi trabajo.',
    'Mi trabajo permite que desarrolle nuevas habilidades.',
    'En mi trabajo puedo aspirar a un mejor puesto.',
    'Durante mi jornada de trabajo puedo tomar pausas cuando las necesito.',
    'Puedo decidir cuanto trabajo realizo durante la jornada laboral.',
    'Puedo decidir la velocidad a la que realizo mis actividades en mi trabajo.',
    'Puedo cambiar el orden de las actividades que realizo en mi trabajo.',
    'Los cambios que se presentan en mi trabajo dificultan mi labor.',
    'Cuando se presentan cambios en mi trabajo se tienen en cuenta mis ideas o aportaciones.',
    'Me informan con claridad cuales son mis funciones.',
    'Me explican claramente los resultados que debo obtener en mi trabajo.',
    'Me explican claramente los objetivos de mi trabajo.',
    'Me informan con quien puedo resolver problemas o asuntos de trabajo.',
    'Me permiten asistir a capacitaciones relacionadas con mi trabajo.',
    'Recibo capacitacion util para hacer mi trabajo.',
    'Mi jefe ayuda a organizar mejor el trabajo.',
    'Mi jefe tiene en cuenta mis puntos de vista y opiniones.',
    'Mi jefe me comunica a tiempo la informacion relacionada con el trabajo.',
    'La orientacion que me da mi jefe me ayuda a realizar mejor mi trabajo.',
    'Mi jefe ayuda a solucionar los problemas que se presentan en el trabajo.',
    'Puedo confiar en mis companeros de trabajo.',
    'Entre companeros solucionamos los problemas de trabajo de forma respetuosa.',
    'En mi trabajo me hacen sentir parte del grupo.',
    'Cuando tenemos que realizar trabajo de equipo los companeros colaboran.',
    'Mis companeros de trabajo me ayudan cuando tengo dificultades.',
    'Me informan sobre lo que hago bien en mi trabajo.',
    'La forma como evaluan mi trabajo en mi centro de trabajo me ayuda a mejorar mi desempeno.',
    'En mi centro de trabajo me pagan a tiempo mi salario.',
    'El pago que recibo es el que merezco por el trabajo que realizo.',
    'Si obtengo los resultados esperados en mi trabajo me recompensan o reconocen.',
    'Las personas que hacen bien el trabajo pueden crecer laboralmente.',
    'Considero que mi trabajo es estable.',
    'En mi trabajo existe continua rotacion de personal.',
    'Siento orgullo de laborar en este centro de trabajo.',
    'Me siento comprometido con mi trabajo.',
    'En mi trabajo puedo expresarme libremente sin interrupciones.',
    'Recibo criticas constantes a mi persona y/o trabajo.',
    'Recibo burlas, calumnias, difamaciones, humillaciones o ridiculizaciones.',
    'Se ignora mi presencia o se me excluye de las reuniones de trabajo y en la toma de decisiones.',
    'Se manipulan las situaciones de trabajo para hacerme parecer un mal trabajador.',
    'Se ignoran mis exitos laborales y se atribuyen a otros trabajadores.',
    'Me bloquean o impiden las oportunidades que tengo para obtener ascenso o mejora en mi trabajo.',
    'He presenciado actos de violencia en mi centro de trabajo.',
]

def _iii_item(num, inversa=False):
    return {'ref': f'III_P{num}', 'texto': GUIA_III_BASE[num - 1], 'inversa': inversa}


CUESTIONARIOS.append({
    'clave': 'III',
    'nombre': 'Identificacion y analisis de los factores de riesgo psicosocial',
    'descripcion': 'Guia de Referencia III - Identificacion y analisis de los factores de riesgo psicosocial.',
    'tamano_min': 1,
    'tamano_max': None,
    'dominios': [
        {'clave': 'D1',  'nombre': 'Carga de trabajo',                        'preguntas': [_iii_item(i) for i in range(1, 6)]},
        {'clave': 'D2',  'nombre': 'Ritmo de trabajo',                        'preguntas': [_iii_item(i) for i in range(6, 9)]},
        {'clave': 'D3',  'nombre': 'Esfuerzo mental',                         'preguntas': [_iii_item(i) for i in range(9, 13)]},
        {'clave': 'D4',  'nombre': 'Actividades y responsabilidades',         'preguntas': [_iii_item(i) for i in range(13, 17)]},
        {'clave': 'D5',  'nombre': 'Jornada de trabajo',                      'preguntas': [_iii_item(i) for i in range(17, 23)]},
        {'clave': 'D6',  'nombre': 'Decisiones en el trabajo',                'preguntas': [_iii_item(i, True) for i in range(23, 29)]},
        {'clave': 'D7',  'nombre': 'Cambios en el trabajo',                   'preguntas': [_iii_item(29, True), _iii_item(30, True)]},
        {'clave': 'D8',  'nombre': 'Capacitacion',                            'preguntas': [_iii_item(i, True) for i in range(31, 37)]},
        {'clave': 'D9',  'nombre': 'Subordinacion',                           'preguntas': [_iii_item(i, True) for i in range(37, 42)]},
        {'clave': 'D10', 'nombre': 'Relaciones con los companeros',           'preguntas': [_iii_item(i, True) for i in range(42, 47)]},
        {
            'clave': 'D11',
            'nombre': 'Rendimiento y reconocimiento',
            'preguntas': (
                [_iii_item(i, True) for i in range(47, 53)]
                + [_iii_item(53, True), _iii_item(54), _iii_item(55, True), _iii_item(56, True)]
            ),
        },
        {
            'clave': 'D12',
            'nombre': 'Violencia laboral',
            'preguntas': [_iii_item(57, True)] + [_iii_item(i) for i in range(58, 65)],
        },
        {
            'clave': 'D13',
            'nombre': 'Atencion a clientes y usuarios',
            'preguntas': [
                {'ref': 'III_CLIENTES', 'texto': 'En mi trabajo debo brindar servicio a clientes o usuarios', 'tipo_respuesta': 'si_no'},
                {'ref': 'III_P65', 'texto': 'Atiendo clientes o usuarios muy enojados.', 'condicion_refs': ['III_CLIENTES'], 'condicion_valor': 1},
                {'ref': 'III_P66', 'texto': 'Mi trabajo me exige atender personas muy necesitadas de ayuda o enfermas.', 'condicion_refs': ['III_CLIENTES'], 'condicion_valor': 1},
                {'ref': 'III_P67', 'texto': 'Para hacer mi trabajo debo demostrar sentimientos distintos a los mios.', 'condicion_refs': ['III_CLIENTES'], 'condicion_valor': 1},
                {'ref': 'III_P68', 'texto': 'Mi trabajo me exige atender situaciones de violencia.', 'condicion_refs': ['III_CLIENTES'], 'condicion_valor': 1},
            ],
        },
        {
            'clave': 'D14',
            'nombre': 'Actitudes de las personas que supervisa',
            'preguntas': [
                {'ref': 'III_SUPERVISOR', 'texto': 'Soy jefe/supervisor de otros trabajadores', 'tipo_respuesta': 'si_no'},
                {'ref': 'III_P69', 'texto': 'Comunican tarde los asuntos de trabajo.', 'condicion_refs': ['III_SUPERVISOR'], 'condicion_valor': 1},
                {'ref': 'III_P70', 'texto': 'Dificultan el logro de los resultados del trabajo.', 'condicion_refs': ['III_SUPERVISOR'], 'condicion_valor': 1},
                {'ref': 'III_P71', 'texto': 'Cooperan poco cuando se necesita.', 'condicion_refs': ['III_SUPERVISOR'], 'condicion_valor': 1},
                {'ref': 'III_P72', 'texto': 'Ignoran las sugerencias para mejorar su trabajo.', 'condicion_refs': ['III_SUPERVISOR'], 'condicion_valor': 1},
            ],
        },
    ],
})
