# Generated by Django 5.2.13 on 2026-04-18 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m00_onboarding', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_accion', to='m00_onboarding.ciclonom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-ciclo__anio'],
                'unique_together': {('tenant', 'ciclo')},
            },
        ),
        migrations.CreateModel(
            name='AccionMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('correctiva', 'Correctiva'), ('mejora', 'Mejora continua')], default='preventiva', max_length=20)),
                ('factor_riesgo', models.CharField(blank=True, max_length=300)),
                ('responsable', models.CharField(max_length=200)),
                ('fecha_limite', models.DateField()),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('avance_notas', models.TextField(blank=True)),
                ('fecha_completado', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='m02_action_plan.planaccion')),
            ],
            options={
                'ordering': ['fecha_limite', 'prioridad'],
            },
        ),
    ]
