# Generated by Django 5.2.13 on 2026-09-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m02_action_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionmedida',
            name='departamento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accionmedida',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accionmedida',
            name='fecha_validacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
